######## New MorphoDynamX session v2.0 r2-805: 2021-01-05 16:26:38

Process.Mesh__System__Load('/media/strauss/LocalHD/Projects/Shanda/Final/Sim Root/root_subd10.mgxm', 'no', 'no', '0')
Process.Mesh__System__Load('/media/strauss/LocalHD/Projects/Shanda/Sim Root/root_subd10.mdxm', 'no', 'no', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('100.0', '100', '0.3', '1', '2', 'TransIso Material')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-805: 2021-01-05 16:41:47
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Save('/media/strauss/LocalHD/Projects/Shanda/Sim Root/root_subd10.mdxm', 'No', '0')
Process.Mesh__System__Load('/media/strauss/LocalHD/Projects/Shanda/Sim Root/202101/root_subd10_100_100.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('100.0', '100', '0.3', '1', '2', 'TransIso Material')
Process.Model__CCF__06_Material_Properties('30', '300', '0.3', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Load('/media/strauss/LocalHD/Projects/Shanda/Sim Root/root_subd10.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('100', '700', '0.3', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Load('/media/strauss/LocalHD/Projects/Shanda/Sim Root/root_subd10.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('100', '500', '0.3', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('100', '500', '0.3', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Save('/media/strauss/LocalHD/Projects/Shanda/Sim Root/root_subd10.mdxm', 'No', '0')
Process.Mesh__System__Load('/media/strauss/LocalHD/Projects/Shanda/Sim Root/202101/root_subd10_100_500.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('90', '600', '0.3', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Save('/media/strauss/LocalHD/Projects/Shanda/Sim Root/root_subd10.mdxm', 'No', '0')
Process.Mesh__System__Load('/media/strauss/LocalHD/Projects/Shanda/Sim Root/202101/root_subd10_90_600.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('90', '600', '0.3', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('50', '500', '0', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-805: 2021-01-09 22:14:43
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__System__Load('/media/strauss/LocalHD/Projects/Shanda/2021 01/EmbrioAnisotropic/MeshTrimmedSubdivided1_growthAssignedInflated.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('50', '1000', '0', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Save('/media/strauss/LocalHD/Projects/Shanda/Sim Root/root_subd10.mdxm', 'No', '0')
Process.Mesh__System__Load('/media/strauss/LocalHD/Projects/Shanda/Sim Root/202101/root_subd10_50_1000_00.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('50', '1000', '0.2', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-805: 2021-01-25 19:03:16
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__System__Load('/media/strauss/LocalHD/Projects/Shanda/2021 01/EmbrioAnisotropic/MeshTrimmedSubdivided1_growthAssignedInflated.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('40', '800', '0.2', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Load('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('40', '600', '0.2', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Save('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10.mdxm', 'No', '0')
Process.Mesh__System__Load('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10_40_600_02.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('40', '1000', '0.15', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Save('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10.mdxm', 'No', '0')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-805: 2021-01-27 17:04:36
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__System__Load('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10.mdxm', 'no', 'no', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('40', '1400', '0.15', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Save('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10.mdxm', 'No', '0')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Separate_3D_Cells('', '', 'No', 'No')
Process.Mesh__Segmentation__Vertex_Labels_From_Volumes()
Process.Mesh__System__Export('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10_40_1400_015.mdxm', 'Text', 'No', '0')
Process.Mesh__System__Load('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10_40_1400_015.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('40', '1200', '0.2', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Load('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('40', '1200', '0.17', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Load('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10.mdxm', 'No', 'No', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('40', '1200', '0', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Mesh__System__Save('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10.mdxm', 'No', '0')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Separate_3D_Cells('', '', 'No', 'No')
Process.Mesh__Segmentation__Vertex_Labels_From_Volumes()
Process.Mesh__System__Export('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10_40_1200_00.mdxm', 'Text', 'No', '0')
Process.Mesh__System__Export('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10_40_1200_00.mdxm', 'Text', 'No', '0')
Process.Mesh__System__Load('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10_40_1200_00.mdxm', 'No', 'No', '0')
Process.Tools__Cell_Maker__Mesh_3D__Tools__Separate_3D_Cells('', '', 'No', 'No')
Process.Mesh__System__Export('/media/BioDataNew/dep_tsiantis/common/01_CURRENT_LAB_MEMBERS/SOEREN/Shanda/root_subd10_40_1200_016.mdxm', 'Text', 'No', '0')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-786: 2021-04-30 12:21:48
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-786: 2021-04-30 12:26:48
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-786: 2021-04-30 12:51:54
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-838: 2021-04-30 14:46:08
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gori/Desktop/model/Liu_Gitlab/root-pressurization-model-for-liu-et-al/EmbrioAnisotropic/Mesh_3x3_2_5-15.mdxm', 'no', 'no', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', '0.5')
Process.Model__CCF__06_Material_Properties('100.0', '100', '0.3', '1', '2', 'TransIso Material')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-917: 2021-07-20 14:41:57
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__System__Load('/home/commonuser/Desktop/models/root-pressurization-model-for-liu-et-al/meshes/cuboid_3x3_2_5-15.mdxm', 'no', 'no', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', 'False', '0.5')
Process.Model__CCF__06_Material_Properties('100.0', '300', '0', '1', '2', 'TransIso Material')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver', 'Model/CCF/13 Growth', 'Model/CCF/14 Subdivide', '49, 46, 32', 'Mesh/System/Save')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/10b Pressure Edge Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-926: 2021-07-20 17:05:22
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-903: 2021-08-09 14:27:21
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__System__Load('', 'No', 'No', '0')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-903: 2021-08-09 15:29:39
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__System__Load('', 'No', 'No', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', 'False', '0.5')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Normal Stress', 'Normal Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material', '1')
Process.Model__CCF__06_Material_Properties('100.0', '300', '0', '1', '2', 'TransIso Material')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', 'False', '0.5')
Process.Model__CCF__06_Material_Properties('100.0', '300', '0', '1', '2', 'TransIso Material')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Normal Stress', 'Normal Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material', '1')
Process.Model__CCF__06_Material_Properties('100.0', '300', '0', '1', '2', 'TransIso Material')
Process.Model__CCF__08a_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '0.1')
Process.Model__CCF__09a_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Mesh__System__Save('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/cylinder_staggered_subd10.mdxm', 'No', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-903: 2021-08-09 17:37:23
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__System__Load('', 'No', 'No', '0')
Process.Tools__System__Save_View('/home/gabriella/root-pressurization-model-for-liu-et-al/EmbrioAnisotropic/FemMembranes.mdxv')
Process.Model__CCF__02_FEM_Solver('10', '0.01', '.0001', '10', '0.1', '10', '0.1', 'Backward Euler', 'Bi-conjugate Gradient Stabilized', '300', '1e-20', 'Yes', '10e-4', 'Model/CCF/05 Stress-Strain', 'Model/CCF/03 Triangle Derivs', 'Model/CCF/10a Pressure Derivs', 'Model/CCF/16 Dirichlet Derivs')
Process.Tools__System__Save_View('/home/gabriella/root-pressurization-model-for-liu-et-al/EmbrioAnisotropic/FemMembranes.mdxv')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Model__CCF__17_Compute_Current_Directions('Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__22_Display_Anisotropy_Propagation_Failure('Linear Triangle', 'Triangle Element', 'E2')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__20_Visualize_Material('Young E2', '', 'Material Labels', 'TransIso Material', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Mesh__System__Load('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/cylinder_staggered_subd10_anisotr100VS300Assigned_P0d5.mdxm', 'No', 'No', '0')
Process.Model__CCF__20_Visualize_Material('Young E2', '', 'Material Labels', 'TransIso Material', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material', 'Linear Triangle', 'Triangle Element')
Process.Mesh__System__Load('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/cylinder_staggered_subd10_pressurized.mdxm', 'No', 'No', '0')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Normal Stress', 'Normal Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material', '1')
Process.Model__CCF__20_Visualize_Material('Young E1E3', '', 'Material Labels', 'TransIso Material', 'Linear Triangle', 'Triangle Element')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', 'False', '0.5')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', 'False', '0.5')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Normal Stress', 'Normal Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material', '1')
Process.Model__CCF__06_Material_Properties('40', '1200', '0.16', '1', '2', 'TransIso Material')
Process.Model__CCF__08_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '1e-6')
Process.Model__CCF__18_Visualize_Directions('Material Direction', 'Growth Direction', '1.0', 'Linear Triangle', 'Triangle Element', '1.e-6')
Process.Model__CCF__09_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Tools__System__Save_View('/home/gabriella/root-pressurization-model-for-liu-et-al/EmbrioAnisotropic/FemMembranes.mdxv')
Process.Mesh__System__Save('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/root_subd10_pressurized_anisotropic_40_1200_016.mdxm', 'No', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Mesh__System__Load('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/root_subd10_pressurized_anisotropic_40_1200_016.mdxm', 'no', 'no', '0')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Normal Stress', 'Normal Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material', '1')
Process.Mesh__System__Load('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/root_subd10_pressurized_isotropic_100_100.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/root_subd10.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/root_subd10_pressurized_anisotropic_40_1200_016.mdxm', 'no', 'no', '0')
Process.Mesh__System__Load('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/root_subd10.mdxm', 'no', 'no', '0')
Process.Model__CCF__04_Reference_Configuration('Linear Triangle', 'Triangle Element', 'False', '0.5')
Process.Model__CCF__05_Stress-Strain('Stress', 'Strain', 'Normal Stress', 'Normal Strain', 'Stress', 'Strain', '1.0', 'Linear Triangle', 'Triangle Element', 'TransIso Material', '1')
Process.Model__CCF__06_Material_Properties('40', '1200', '0.16', '1', '2', 'TransIso Material')
Process.Model__CCF__08_Set_Aniso_Dir('Linear Triangle', 'Triangle Element', 'E2', '0.0 0.0 1.0', 'Orthogonal', '1e-6')
Process.Model__CCF__09_Set_Pressure('0.5', '1', 'Fem Pressure', 'Triangle Element')
Process.Mesh__System__Save('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/root_subd10.mdxm', 'No', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Model__CCF__06_Material_Properties('100', '100', '0.16', '1', '2', 'TransIso Material')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-931: 2021-08-10 12:19:48
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/root_subd10_pressurized_anisotropic_40_1200_016.mdxm', 'No', 'No', '0')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-931: 2021-08-10 13:16:20
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/root_subd10_pressurized_anisotropic_40_1200_016.mdxm', 'No', 'No', '0')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Model__CCF__01_FEM_Membranes('Model/CCF/02 FEM Solver')
Process.Tools__System__Load_View('FemMembranes.mdxv')
######## New MorphoDynamX session v2.0 r2-931: 2021-08-12 11:25:31
Process.Tools__System__Load_View('FemMembranes.mdxv')
Process.Mesh__System__Load('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/root_subd10_aniso_40_1200_nu0d16_assigned.mdxm', 'no', 'no', '0')
Process.Mesh__System__Save('/home/gabriella/root-pressurization-model-for-liu-et-al/meshes/root_subd10_aniso_40_1200_nu0d16_assigned.mdxm', 'No', '0')
Process.Mesh__System__Save('/home/gabriella/root-pressurization-model-for-liu-et-al/EmbrioAnisotropic/root_subd10_aniso_40_1200_nu0d16_assigned.mdxm', 'No', '0')
Process.Tools__System__Save_View('/home/gabriella/root-pressurization-model-for-liu-et-al/EmbrioAnisotropic/FemMembranes.mdxv')
